<?php

return [
    [
        'title' => 'সার্বিয়া সুনামধন্য কোম্পানিতে ওয়ার্ক পারমিট ভিসা কাজের সুবর্ণ সুযোগ। যোগাযোগ :01918829697',
        'image' => 'images/events/serbia.jpg',
        'date' => 'Apr 17 - Apr 25',
        'organizer' => 'BIWPS',
        'category' => 'বারিস্টা/কফি মেকার, অ্যাসিস্ট্যান্ট শেফ, অ্যাসিস্ট্যান্ট ওয়েটার',
        'excerpt' => null,
        'slug' => 'serbia-work-permit-opportunity',
    ],
    [
        'title' => 'সৌদি আরবের সুনামধন্য কোম্পানিতে ওয়ার্ক পারমিট ভিসা কাজের সুবর্ণ সুযোগ। যোগাযোগ :01918829697',
        'image' => 'images/events/saudi-gcs.png',
        'date' => 'Apr 17 - Apr 20',
        'organizer' => 'BIWPS',
        'category' => 'E.T.C',
        'excerpt' => null,
        'slug' => 'saudi-arabia-work-permit-opportunity',
    ],
    [
        'title' => 'BIWPS-Babul International Work Permit Solutions এর পক্ষ থেকে ভিয়েতনামের যাওয়ার সুবর্ন সুযোগ।',
        'image' => 'images/events/vietnam.png',
        'date' => 'Apr 20 - Apr 27',
        'organizer' => 'BIWPS',
        'category' => '1',
        'excerpt' => 'ভিয়েতনাম ডেলিগেট ইন্টারভিউ এর মাধ্যমে নিয়োগ বিজ্ঞপ্তি। কোম্পানির নাম: DaiDung Corporation...',
        'slug' => 'vietnam-delegate-interview',
    ],
    [
        'title' => 'BIWPS-Babul International Work Permit Solutions এর পক্ষ থেকে নিউজিল্যান্ডে নিয়োগ বিজ্ঞপ্তি',
        'image' => 'images/events/newzealand.png',
        'date' => 'Apr 20 - Apr 30',
        'organizer' => 'BIWPS',
        'category' => '2',
        'excerpt' => 'নিউজিল্যান্ডে নিয়োগ বিজ্ঞপ্তি — কাজের ধরন, সংখ্যা, যোগ্যতা ও বেতন সংক্রান্ত বিস্তারিত...',
        'slug' => 'newzealand-recruitment-notice',
    ],
    [
        'title' => 'BIWPS-Babul International Work Permit Solutions এর পক্ষ থেকে দুবাইয়ে জরুরি নিয়োগ বিজ্ঞপ্তি',
        'image' => 'images/events/dubai.jpg',
        'date' => 'Apr 22 - Apr 30',
        'organizer' => 'BIWPS',
        'category' => '1',
        'excerpt' => 'সংযুক্ত আরব আমিরাত (UAE) — দুবাইয়ে জরুরি নিয়োগ বিজ্ঞপ্তি। প্রি সিলেকশন চলছে...',
        'slug' => 'dubai-urgent-recruitment',
    ],
    [
        'title' => 'BIWPS-Babul International Work Permit Solutions এর পক্ষ থেকে মরিশাসে জরুরি নিয়োগ বিজ্ঞপ্তি',
        'image' => 'images/events/mauritius.jpg',
        'date' => 'Apr 23 - Apr 28',
        'organizer' => 'BIWPS',
        'category' => '1',
        'excerpt' => 'মরিশাসে জরুরি নিয়োগ বিজ্ঞপ্তি। ফাইনাল ইন্টারভিউ তারিখ: ২৭ ও ২৮ এপ্রিল ২০২৬ ইং...',
        'slug' => 'mauritius-urgent-recruitment',
    ],
    [
        'title' => 'সৌদি আরবে নিয়োগ বিজ্ঞপ্তি।',
        'image' => 'images/events/saudi-recruit.jpg',
        'date' => 'Apr 26 - May 10',
        'organizer' => 'BIWPS',
        'category' => null,
        'excerpt' => 'যোগাযোগ: 01918-829697, 01609674606। অফিস: হাউজ #529-525, হাজী আলম রোড, দিয়াবাড়ি, উত্তরা, ঢাকা-1230',
        'slug' => 'saudi-arabia-recruitment-notice',
    ],
    [
        'title' => 'রাশিয়ায় কর্মী নিয়োগ বিজ্ঞপ্তি — বাংলাদেশ থেকে বিশ্বস্ত কোম্পানিতে জরুরি ভিত্তিতে নিয়োগ চলছে।',
        'image' => 'images/events/russia.png',
        'date' => 'Apr 27 - May 10',
        'organizer' => 'BIWPS',
        'category' => null,
        'excerpt' => 'রাশিয়ায় কর্মী নিয়োগ চলছে। পদের নাম ও ধরনসহ বিস্তারিত তথ্য দেখুন...',
        'slug' => 'russia-worker-recruitment',
    ],
    [
        'title' => 'BIWPS-Babul International Work Permit Solutions এর পক্ষ থেকে শ্রীলঙ্কায় জরুরি নিয়োগ বিজ্ঞপ্তি',
        'image' => 'images/events/srilanka.jpg',
        'date' => 'Apr 30 - May 14',
        'organizer' => 'BIWPS',
        'category' => null,
        'excerpt' => 'COMPANY: CHINA HARBOUR ENG. COMPANY — ফাইনাল ইন্টারভিউসহ বিস্তারিত...',
        'slug' => 'srilanka-urgent-recruitment',
    ],
    [
        'title' => 'BIWPS-Babul International Work Permit Solutions এর পক্ষ থেকে শেনজেন ভুক্ত দেশ বুলগেরিয়ায় জরুরি নিয়োগ বিজ্ঞপ্তি',
        'image' => 'images/events/event-10.jpg',
        'date' => 'May 02 - May 15',
        'organizer' => 'BIWPS',
        'category' => '2',
        'excerpt' => 'শেনজেন ভুক্ত দেশ বুলগেরিয়ায় জরুরি নিয়োগ বিজ্ঞপ্তি। সিভি সিলেকশন চলছে...',
        'slug' => 'bulgaria-schengen-urgent-recruitment',
    ],
    [
        'title' => 'BIWPS-Babul International Work Permit Solutions এর পক্ষ থেকে সৌদি আরবে জরুরি নিয়োগ বিজ্ঞপ্তি',
        'image' => 'images/events/event-11.jpg',
        'date' => 'May 14 - May 20',
        'organizer' => 'BIWPS',
        'category' => null,
        'excerpt' => 'কোম্পানি: International Maritime Industries (IMI) — সৌদি আরবে জরুরি নিয়োগ বিজ্ঞপ্তি...',
        'slug' => 'saudi-imi-urgent-recruitment',
    ],
    [
        'title' => 'AYTB Saudi Arabia CV Collection & Interview Event – 27-28 March 2026 | BIWPS',
        'image' => 'images/events/event-12.png',
        'date' => 'May 20 - May 27',
        'organizer' => 'BIWPS',
        'category' => 'Technician',
        'excerpt' => 'Urgent Recruitment Event: AYTB Industrial Contracting – Saudi Arabia. Join BIWPS for an exclusive two-day...',
        'slug' => 'aytb-saudi-cv-collection-interview',
    ],
];
